# -*- python -*-

import os
Import('*')

root_src_conf = os.path.join(mi_config.tmpdir, 'root.src.conf')

env['root_src_conf'] = root_src_conf

depInstall(env, 'root.src.conf',
           '$root_src_conf/etc/init.d',
           ['apply-dbgopts'])

dbgopts_cmds = ['echo "#/bin/sh" > $TARGET',
                'echo "/bin/mkdir -p /tmpfs/debug" >> $TARGET']
for opt in mi_config.debugopts:
    dbgopts_cmds.append('echo "cat /dev/null > /tmpfs/debug/%s" >> $TARGET' % opt)
dbgopts_cmds.append('chmod +x $TARGET')

env.Command('apply-dbgopts', [], dbgopts_cmds)

del env['root_src_conf']
