# -*- python -*-
# Copyright (C) 2007, Levin Du.
# Author:  Levin Du <zsdjw@21cn.com>
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANT; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public LIcense for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.

Import('env', 'mi_config', 'MiPkgMaker')

class PartedBinMaker(MiPkgMaker):
    alias = 'parted.bin'
    name = 'parted'
    version = '1.8.8'
    package_bin = '${package}.bin.tar.gz'
    source_list = ['${package}.tar.gz']
    pack_prefix = '#bindir/root'
    conf_cmds = ['cd $build_prefix; ' \
                 './configure --prefix=/usr ' \
                 ' --without-readline' \
                 ' --disable-nls' \
                 ' --disable-rpath' \
                 ' --enable-Werror=no']

    install_cmds = ['make -C $build_prefix' \
                    ' DESTDIR=$install_prefix ' \
                    ' install']

pkg = PartedBinMaker(env)
pkg.make()
