#!/bin/bash
## Note: this script run in MI environment, no in the chroot target system.
# parameters:
# $1 <tgtsys_root> is the target system mount path.

./scripts/arch-genfstab -p $1 >> /etc/fstab
exit $?

