#!/bin/bash
## Note: run in target system
# parameters:
#    $1 <distkernelver> target system kernel version, pass from magicinstaller

/sbin/new-kernel-pkg --mkinitrd --dracut --depmod --update $1
exit $?

