#!/bin/sh
# $rc_base/init.d/setclock

. /etc/sysconfig/rc
. ${rc_functions}
. /etc/sysconfig/clock

case "${UTC}" in
	yes|true|1)
		CLOCKPARAMS="${CLOCKPARAMS} --utc"
		;;

	no|false|0)
		CLOCKPARAMS="${CLOCKPARAMS} --localtime"
		;;

esac

case ${1} in
	start)
		boot_mesg "Setting system clock..."
		hwclock --hctosys ${CLOCKPARAMS} >/dev/null
		evaluate_retval
		;;

	stop)
		boot_mesg "Setting hardware clock..."
		hwclock --systohc ${CLOCKPARAMS} >/dev/null
		evaluate_retval
		;;

	*)
		echo "Usage: ${0} {start|stop}"
		;;

esac
