# -*- python -*-
# Copyright (C) 2003, Charles Wang.
# Author:  Charles Wang <charles@linux.net.cn>
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANT; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public LIcense for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.


if 'root.step1' in COMMAND_LINE_TARGETS:
    SConscript('root.step1/SConscript')

if 'root.arch1' in COMMAND_LINE_TARGETS:
    SConscript('root.arch1/SConscript')

elif 'busybox.bin' in COMMAND_LINE_TARGETS:
    SConscript('busybox/SConscript')

elif 'parted.bin' in COMMAND_LINE_TARGETS:
    SConscript('parted/SConscript')

elif 'kernel.copy' in COMMAND_LINE_TARGETS:
    SConscript('kernel_copy/SConscript')

elif 'kernel.build' in COMMAND_LINE_TARGETS:
    SConscript('kernel_build/SConscript')
else:
    SConscript('bootscripts/SConscript')

