# -*- python -*-
# Copyright (C) 2003, Charles Wang.
# Author:  Charles Wang <charles@linux.net.cn>
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANT; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public LIcense for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.
# -*- python -*-
import os
import sys
import string
Import('*')

##### Construct the tar.gz which needed by rootfs.
## include: 
#           #bindir/root.step1.tar.gz
#           #bindir/root.bootscripts.tar.gz
#           #bindir/kmodules-x.xx.xx.tar.bz2
#           #bindir/mi-vmlinuz-x.xx.xx  (needed by iso)

def add_root_target(tname, tname_bootscripts):
    if DEF_ROOTFS == tname and TARGET_BUILD_VARIANT == 'eng':
        if 'root.step1' in COMMAND_LINE_TARGETS:
            SConscript('%s/SConscript' % tname)
            print 'include', '%s/SConscript' % tname

    if DEF_ROOTFS == tname:
        SConscript('%s/SConscript' % tname_bootscripts)

## TARGET: root.step1
## TARGET: root.bootscripts
add_root_target('root.magic1', 'bootscripts.magic1')
add_root_target('root.arch1', 'bootscripts.arch1')
add_root_target('root.magic64', 'bootscripts.arch1')

## TARGET: busybox.bin
#SConscript('busybox/SConscript')

## TARGET: 'parted.bin'
#SConscript('parted/SConscript')

## TARGET: 'kernel.copy'
#SConscript('kernel_copy/SConscript')

## TARGET: 'kernel.build'
#SConscript('kernel_build/SConscript')
