# -*- python -*-
# Copyright (C) 2003, Charles Wang.
# Author:  Charles Wang <charles@linux.net.cn>
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANT; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public LIcense for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.
# -*- python -*-
import os
import sys
import string
Import('*')

##### Construct the tar.gz which needed by rootfs.
## include: 
#           #bindir/root.step1.tar.gz
#           #bindir/root.bootscripts.tar.gz
#           #bindir/kmodules-x.xx.xx.tar.bz2
#           #bindir/mi-vmlinuz-x.xx.xx  (needed by iso)
products = env['PRODUCTS']
## TARGET: root.step1
## TARGET: root.bootscripts
rootfs_name = products[TARGET_PRODUCT]['PRODUCT_ROOTFS']
if TARGET_BUILD_VARIANT == 'eng' and 'root.step1' in COMMAND_LINE_TARGETS:
    SConscript('root.%s/SConscript' % rootfs_name)
    print 'include', 'root.%s/SConscript' % rootfs_name

SConscript('bootscripts.%s/SConscript' % rootfs_name)


## TARGET: busybox.bin
#SConscript('busybox/SConscript')

## TARGET: 'parted.bin'
#SConscript('parted/SConscript')

## TARGET: 'kernel.copy'
#SConscript('kernel_copy/SConscript')

## TARGET: 'kernel.build'
#SConscript('kernel_build/SConscript')
