# -*- python -*-
# Copyright (C) 2003, Charles Wang.
# Author:  Charles Wang <charles@linux.net.cn>
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANT; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public LIcense for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.

import os
Import('*')

root_bs = os.path.join(mi_config.tmpdir, 'bootscripts.arch1')

depInstallDir(env, 'bootscripts.arch1', root_bs,
                    srcdirs=['etc', 
                             'root'])

##### Construct the #bindir/root.bootscripts.tar.gz
pkg = 'root.bootscripts.arch1.tar.gz'
__root_bs = env.Command('#bindir/%s' % pkg, env.Alias('bootscripts.arch1'),
            [ getSudoSh("tar c -C %s . | gzip -9 > $TARGET" % root_bs) ])

env.Alias('rootfs', env.Command('#bindir/root.bootscripts.tar.gz', __root_bs,
        '[ -L $TARGET ] && rm $TARGET; ln -sv %s $TARGET' % pkg))
