#!/bin/sh
# Copyright (C) 2003, Charles Wang.
# Author:  Charles Wang <charles@linux.net.cn>
# All rights reserved.
# License: GPL

# It is required if the SCSI harddisk is exists.
#/sbin/modprobe  sd_mod
