# -*- python -*-
# Copyright (C) 2013, Zhang Yang.
# Author:  Zhang Yang <zy.netsec@gmail.com>
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANT; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public LIcense for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.
import glob
Import('*')

LOCAL_PATH = _my_dir()

MI_data(glob.glob('%s/*.py' % LOCAL_PATH), 'mi/server/')
MI_data(glob.glob('%s/operations/*.py' % LOCAL_PATH), 'mi/server/operations/')
MI_data(glob.glob('%s/utils/*.py' % LOCAL_PATH), 'mi/server/utils/')
MI_data(glob.glob('%s/utils/rpm/*.py' % LOCAL_PATH), 'mi/server/utils/rpm/')
MI_data(glob.glob('%s/utils/tar/*.py' % LOCAL_PATH), 'mi/server/utils/tar/')
MI_data(glob.glob('%s/utils/yum/*.py' % LOCAL_PATH), 'mi/server/utils/yum/')

