#!/bin/sh
# $rc_base/init.d/halt

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
    stop)
        # busybox have a poweroff to get the system down.
        poweroff -d 1
        ;;
    *)
        echo "Usage: {stop}"
        exit 1
        ;;
esac

