#!/bin/sh
# $rc_base/init.d/

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
    start)
        boot_mesg "Remounting root file system in read-write mode..."
        mount -a >/dev/null
        evaluate_retval
        ;;
    stop)
        boot_mesg "Unmounting all other currently mounted file systems..."
        ;;
    *)
        echo "Usage: ${0} {start|stop}"
        exit 1
        ;;
esac

