#!/bin/sh
# Copyright (C) 2003, Charles Wang.
# Author:  Charles Wang <charles@linux.net.cn>
# All rights reserved.
# License: GPL

export PATH=/usr/bin:/bin:/usr/sbin:/sbin

. /etc/sysconfig/i18n.zh_CN
export GDK_USE_XFT=0

# Run the init script one by one.
# Please don't change the order arbitrarily.
/etc/init.d/mountall start
/etc/init.d/udev start
/etc/init.d/modules
/etc/init.d/syslogd
/etc/init.d/network

# For magicinstaller.
#/etc/init.d/tftpd
# For magicinstaller debug.
#/etc/init.d/create-devenv
#/etc/init.d/apply-dbgopts
