#!/bin/sh
# Copyright (C) 2003, Charles Wang.
# Author:  Charles Wang <charles@linux.net.cn>
# All rights reserved.
# License: GPL

/bin/mkdir -p /tmpfs/tftpboot
# Use in.tftpd might cause security problem. Hostile program can
# upload files until all of the memory is consumed.
/usr/sbin/in.tftpd -l -c -u root -s /tmpfs/tftpboot
