#!/bin/sh
########################################################################
# Begin $rc_base/init.d/reboot
#
# Description : Reboot Scripts
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	stop)
		boot_mesg "Restarting system..."
        # Notice: -i Shut down all network interfaces just before halt or reboot.
        #         but the reboot in busybox not have this option.
		#reboot -d -f -i
        reboot -d 1 -f
		;;

	*)
		echo "Usage: ${0} {stop}"
		exit 1
		;;

esac

# End $rc_base/init.d/reboot
