#!/bin/sh
# $rc_bash/init.d/sysctl

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
    start)
        if [ -f "/etc/sysctl.conf" ]; then
            boot_mesg "Setting kernel runtime parameters..."
            # Notice: busybox's sysctl command have no -q option.
            # We don not use /etc/sysctl.conf to set the kernel. So 
            # keep the -q option here, if you will use this function 
            # in busybox, please drop the -q option.
            sysctl -q -p
            evaluate_retval
        fi
        ;;

    status)
        sysctl -a
        ;;

    *)
        echo "Usage: ${0} {start|status}"
        exit 1
        ;;
esac

